### ISSUE TITLE
PHP Deprecated:  Return type of EasyRdf\Resource::offsetExists($offset)

### ISSUE THREAD

**Issue by JoeThielen** [sweetrdf/easyrdf#34]
PHP 8.2.9, got this note from serialise('turtle') - after creating a new blank graph adding one triple (via add()).  No notices if I run serialize('ntriples').

PHP Deprecated:  Return type of EasyRdf\Resource::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /XXX/vendor/easyrdf/easyrdf/lib/Resource.php on line 772

PHP Deprecated:  Return type of EasyRdf\Resource::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /XXX/vendor/easyrdf/easyrdf/lib/Resource.php on line 789

PHP Deprecated:  Return type of EasyRdf\Resource::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /XXX/vendor/easyrdf/easyrdf/lib/Resource.php on line 807

PHP Deprecated:  Return type of EasyRdf\Resource::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /XXX/vendor/easyrdf/easyrdf/lib/Resource.php on line 824

**Comment by k00ni** [comment]
Thank you for reporting. I will look into that.

**Comment by k00ni** [comment]
I can't reproduce the bug.

My setup is Docker container `8.2-cli` (running PHP 8.2.9). I played around with a few `add`-calls, but these deprecations weren't triggered. Its also not clear why they occur, because I marked these functions already with `#[\ReturnTypeWillChange]`, as you can see here for instance: https://github.com/sweetrdf/easyrdf/blob/master/lib/Resource.php#L800

Running tests on 8.2 only leads to 70+ deprecations because of ARC2.

Please post your example code. A complete, failing test would be great.

**Comment by JoeThielen** [comment]
I'm sorry Konrad.  I had easyrdf/easyrdf loaded instead of sweetrdf/easyrdf.  You are correct, your version does not complain.

Thank you so much for picking up this project and keeping it going!
